# 도커 관련 설정 파일

version: '3.8'

services:
  # PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:15-alpine                                                       # 사용할 도커 이미지
    container_name: discodeit-db                                                    # 생성될 DB 컨테이너의 이름
    env_file: .env                                                                  # 환경 변수 파일
    ports:
      - "5432:5432"                                                                 # 포트 포워딩 (내 컴퓨터 포트 : 컨테이너 내부 포트)
    volumes:
      - pgdata:/var/lib/postgresql/data                                             # DB 데이터 영구 보장
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql      # DB 생성 시, 실행할 SQL 파일 연결
    restart: always                                                                 # DB 다운 시, 자동으로 재실행

  # Spring Boot 애플리케이션 서비스
  app:
    build:
      context: .                                                                    # 현재 폴더에 있는 Dockerfile을 사용하여 이미지 빌드
    container_name: discodeit-app                                                   # 생성될 App 컨테이너의 이름
    env_file: .env                                                                  # 환경 변수 파일
    ports:
      - "8081:8080"                                                                 # 포트 포워딩 (내 컴퓨터 포트 : 컨테이너 내부 포트)
    depends_on:
      - db                                                                          # 서비스 간 의존성 설정 = DB 서비스 우선 수행
    volumes:
      - appdata:/app/BinaryContentStorage                                           # BinaryContentStorage 데이터 영구 저장

# 볼륨 정의
volumes:
  pgdata:                                                                           # DB의 실제 데이터가 저장되는 가상 디스크
  appdata:                                                                          # App에서 생성한 로컬 파일들이 저장되는 가상 디스크