spring:
  application:                                            # 프로젝트 고유 이름
    name: discodeit

  datasource:                                             # 데이터베이스 연결 설정 값
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver              # PostgreSQL 전용 드라이버

  jpa:
    hibernate:                                            # 엔티티 - DB 테이블이 일치 여부 확인
      ddl-auto: update

    show-sql: true                                        # 실행되는 SQL 문을 콘솔에 출력

    properties:                                           # SQL 로그 설정 값
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    open-in-view: false                                   # 트랜잭션 밖에서 지연 로딩 방지

  sql:                                                    # 애플리케이션 실행 시, schema.sql 항상 실행
    init:
      mode: always

logging:                                                  # 로깅 설정 값
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.jdbc.extract: trace

discodeit:                                                # 커스텀 설정 값
  repository:                                             # 데이터 저장소 타입
    type: jpa
    file-directory: .discodeit

  storage:                                                # 로컬 저장소 설정 값
    type: local
    local:
      root-path: ./upload-files

springdoc:                                                # Swagger 설정 값
  api-docs:
    enabled: true                                         # API 명세서 자동 생성
    path: /api-docs                                       # OpenAPI Spec 추출 경로

  swagger-ui:
    enabled: true                                         # 웹 브라우저 UI 활성화
    path: /docs
    groups-order: DESC                                    # 그룹 정렬 순서
    operations-sorter: method                             # GET, POST 순서 정렬

  default-consumes-media-type: application/json           # 기본 요청 / 응답 형식 = JSON
  default-produces-media-type: application/json