name: CD Test

# 작동 조건 설정
on:
  push:                                         # release 브랜치에 push 될 때만 실행
    branches: [ "release" ]

# 작업 설정
jobs:
  deploy:
    runs-on: ubuntu-latest                      # 작동할 운영체제 환경

    steps:
      - name: 1. 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: 2. AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: 3. Amazon ECR (public) 로그인
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: 4. Docker 이미지 빌드 및 푸시 (latest & SHA 태그)
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY_URI }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:latest -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: 5. AWS 인증 재설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: 6. 기존 서비스 중단 (프리티어 절약 desired-count 0)
        run: |
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER }} --service ${{ vars.ECS_SERVICE }} --desired-count 0
          aws ecs wait services-stable --cluster ${{ vars.ECS_CLUSTER }} --services ${{ vars.ECS_SERVICE }}

      - name: 7. 새 태스크 정의 등록 및 서비스 재시작
        run: |
          TASK_DEF=$(aws ecs describe-task-definition --task-definition ${{ vars.ECS_TASK_DEFINITION }})
          NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "${{ vars.ECR_REPOSITORY_URI }}:${{ github.sha }}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
          
          NEW_REV=$(aws ecs register-task-definition --cli-input-json "$NEW_TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)
          
          aws ecs update-service --cluster ${{ vars.ECS_CLUSTER }} --service ${{ vars.ECS_SERVICE }} --task-definition $NEW_REV --desired-count 1